services:
  postgres:
    image: postgres:16
    container_name: tareas-postgres
    environment:
      POSTGRES_DB: tareas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - tareas_postgres_data:/var/lib/postgresql/data

volumes:
  tareas_postgres_data:
