spring.application.name=tareas-backend
debug=false

server.port=8080
server.servlet.context-path=/api

spring.datasource.url=${TAREAS_DB_URL:jdbc:postgresql://localhost:5432/tareas_db}
spring.datasource.username=${TAREAS_DB_USERNAME:postgres}
spring.datasource.password=${TAREAS_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
