spring.application.name=tareas-backend
debug=false
logging.level.root=INFO
logging.level.org.springframework=INFO

server.port=8080
server.servlet.context-path=/api
tareas.storage.path=${user.dir}/data/tareas.json
